# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'address_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Add
from PyQt5 import QtCore, QtGui, QtWidgets
from addressbook_db import AddressBookDB


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 295)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 381, 271))
        self.tabWidget.setObjectName("tabWidget")
        self.entryName = QtWidgets.QWidget()
        self.entryName.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.entryName.setObjectName("entryName")
        self.cellNumber_input = QtWidgets.QLineEdit(self.entryName)
        self.cellNumber_input.setGeometry(QtCore.QRect(10, 130, 171, 25))
        self.cellNumber_input.setObjectName("cellNumber_input")
        self.edit_button = QtWidgets.QPushButton(self.entryName)
        self.edit_button.setGeometry(QtCore.QRect(260, 40, 91, 25))
        self.edit_button.setObjectName("edit_button")
        self.clear_button = QtWidgets.QPushButton(self.entryName)
        self.clear_button.setGeometry(QtCore.QRect(260, 70, 91, 25))
        self.clear_button.setObjectName("clear_button")
        self.id_input = QtWidgets.QLineEdit(self.entryName)
        self.id_input.setGeometry(QtCore.QRect(10, 10, 81, 25))
        self.id_input.setObjectName("id_input")
        self.address_input = QtWidgets.QLineEdit(self.entryName)
        self.address_input.setGeometry(QtCore.QRect(10, 100, 211, 25))
        self.address_input.setObjectName("address_input")
        self.search_entry_button = QtWidgets.QPushButton(self.entryName)
        self.search_entry_button.setGeometry(QtCore.QRect(100, 10, 61, 25))
        self.search_entry_button.setObjectName("search_entry_button")
        self.initial_input = QtWidgets.QLineEdit(self.entryName)
        self.initial_input.setGeometry(QtCore.QRect(170, 40, 51, 25))
        self.initial_input.setObjectName("initial_input")
        self.city_input = QtWidgets.QLineEdit(self.entryName)
        self.city_input.setGeometry(QtCore.QRect(10, 160, 121, 25))
        self.city_input.setObjectName("city_input")
        self.add_button = QtWidgets.QPushButton(self.entryName)
        self.add_button.setGeometry(QtCore.QRect(260, 10, 91, 25))
        self.add_button.setObjectName("add_button")
        self.lastName_input = QtWidgets.QLineEdit(self.entryName)
        self.lastName_input.setGeometry(QtCore.QRect(10, 70, 151, 25))
        self.lastName_input.setObjectName("lastName_input")
        self.firstName_input = QtWidgets.QLineEdit(self.entryName)
        self.firstName_input.setGeometry(QtCore.QRect(10, 40, 151, 25))
        self.firstName_input.setObjectName("firstName_input")
        self.tabWidget.addTab(self.entryName, "")
        self.recordTab = QtWidgets.QWidget()
        self.recordTab.setObjectName("recordTab")
        self.search_bar = QtWidgets.QLineEdit(self.recordTab)
        self.search_bar.setGeometry(QtCore.QRect(10, 10, 251, 25))
        self.search_bar.setObjectName("search_bar")
        self.search_record_button = QtWidgets.QPushButton(self.recordTab)
        self.search_record_button.setGeometry(QtCore.QRect(270, 10, 89, 25))
        self.search_record_button.setObjectName("search_record_button")
        self.record_detail = QtWidgets.QTextEdit(self.recordTab)
        self.record_detail.setGeometry(QtCore.QRect(10, 50, 351, 181))
        self.record_detail.setObjectName("record_detail")
        self.tabWidget.addTab(self.recordTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.id_input.setEnabled(False)

        #Used for Creating, Editing, and Display Contacts
        self.address_book_db = AddressBookDB()
        self.id_input.setText(self.address_book_db.get_id())
        self.add_button.clicked.connect(self.add_contact)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cellNumber_input.setPlaceholderText(_translate("MainWindow", "Cell#"))
        self.edit_button.setText(_translate("MainWindow", "Edit"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.id_input.setPlaceholderText(_translate("MainWindow", "ID"))
        self.address_input.setPlaceholderText(_translate("MainWindow", "Address"))
        self.search_entry_button.setText(_translate("MainWindow", "Search"))
        self.initial_input.setPlaceholderText(_translate("MainWindow", "M.I."))
        self.city_input.setPlaceholderText(_translate("MainWindow", "City"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.lastName_input.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.firstName_input.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.entryName), _translate("MainWindow", "Tab 1"))
        self.search_bar.setPlaceholderText(_translate("MainWindow", "ID"))
        self.search_record_button.setText(_translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recordTab), _translate("MainWindow", "Tab 2"))

    def add_contact(self):
        first_name = self.firstName_input.text()
        last_name = self.lastName_input.text()
        initial = self.initial_input.text()
        address = self.address_input.text()
        city = self.city_input.text()

        result = self.address_book_db.add_contact(first_name, initial, last_name, address, city)
        self.id_input.setText(self.address_book_db.get_id())
        
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Add Contact")
        msg.setText(result)

        msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
