# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cipher.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from random import randint


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 334)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 0, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.encryption_input = QtWidgets.QLineEdit(self.centralwidget)
        self.encryption_input.setGeometry(QtCore.QRect(90, 50, 261, 41))
        self.encryption_input.setObjectName("encryption_input")
        self.cipher_button = QtWidgets.QPushButton(self.centralwidget)
        self.cipher_button.setGeometry(QtCore.QRect(120, 100, 201, 25))
        self.cipher_button.setObjectName("cipher_button")
        self.decryption_input = QtWidgets.QLineEdit(self.centralwidget)
        self.decryption_input.setEnabled(True)
        self.decryption_input.setGeometry(QtCore.QRect(90, 150, 261, 41))
        self.decryption_input.setObjectName("decryption_input")
        self.decipher_button = QtWidgets.QPushButton(self.centralwidget)
        self.decipher_button.setGeometry(QtCore.QRect(120, 200, 201, 25))
        self.decipher_button.setObjectName("decipher_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Used to interact with the cipher and decipher button
        self.shifter = 0
        self.cipher_button.clicked.connect(self.encryption_press)
        self.decipher_button.clicked.connect(self.decryption_press)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cipher Program"))
        self.cipher_button.setText(_translate("MainWindow", "Encrypt"))
        self.decipher_button.setText(_translate("MainWindow", "Decrypt"))  
    
    def encryption_press(self):
        extracted_text = self.encryption_input.text()

        print(extracted_text)
        # Pick a random shifter
        self.shifter = randint(0, 25)        
        message = "".join([chr(ord(character)+self.shifter) for character in [*extracted_text]])
        self.decryption_input.setText(message)
    
    def decryption_press(self):
        extracted_text = self.decryption_input.text()

        message = "".join([chr(ord(character)-self.shifter) for character in [*extracted_text]])
        self.encryption_input.setText(message)
